### ISSUE TITLE
Samplesheet parsing

### ISSUE THREAD

**Issue by jamestwebber** [czbiohub/bcl2fastr#39]
To properly demux a run we'll need to parse the samplesheet, which is a CSV, and map the indexes (allowing for errors) to the samples.

 - [ ] Read in samplesheet (`csv` file) and extract information about sample names and indexes (see https://github.com/czbiohub/seqbot/blob/master/src/seqbot/bcl2fastr/write_fastq.py#L31) for example in Python).
 - [ ] Compute all indexes of hamming distance 1 to the sample indexes–worth looking for a crate to help with this but should be fast in any case.
  See https://github.com/czbiohub/seqbot/blob/master/src/seqbot/util.py#L81 for Python implementation of a `hamming_set`, which is the set of all strings within one base of an input string. The function `hamming_conflict`, below, tests whether a given samplesheet has overlapping hamming sets.

**Comment by phoenixAja** [comment]
@jamestwebber can we touch base about this tomorrow and go through the existing bcl2fastr python files?

**Comment by jamestwebber** [comment]
Sure let's find a time
