### ISSUE TITLE
test data

### ISSUE THREAD

**Issue by jamestwebber** [czbiohub/bcl2fastr#4]
We can use the run 190414_A00111_0296_AHJCWWDSXX for testing.

- [x] The raw data is read-only in `/mnt/ibm_seqdata/NovaSeq-1/190414_A00111_0296_AHJCWWDSXX`
- [x] fastqs and the samplesheet are in `/mnt/data_lg/seqbot/test_data` (should be readable)
- [x] Subset the fastq files to a single tile (e.g. 1101) to get a small test dataset

**Comment by phoenixAja** [comment]
fixed
