### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by jamestwebber** [czbiohub/bcl2fastr#62]
While working on the index_count branch I added some `println` messages for timing/debugging purposes but it'd be better to use a proper logger with timestamps. Not sure what's out there for rust but I'm sure there's something.

**Comment by jamestwebber** [comment]
It looks like either the [log](https://crates.io/crates/log) and [env_logger](https://crates.io/crates/env_logger) crates would do the trick here. There are a couple other options besides `env_logger` but that ones seems to be popular.

**Comment by phoenixAja** [comment]
i think we should tackle this before parallelizing. @jamestwebber have you started working on this yet?
