### ISSUE TITLE
UMI support?

### ISSUE THREAD

**Issue by brainstorm** [czbiohub/bcl2fastr#87]
Is it in the roadmap? BclConvert supports it, I was wondering if there's plans to support it in here? :)

https://support.illumina.com/downloads/bcl-convert-downloads.html

**Comment by jamestwebber** [comment]
Whoa an issue! Sorry, wasn't monitoring this repo at all.

The truth is: there is no roadmap. I no longer work at CZ Biohub and I'm not sure what the status of this project will be in the future. As my current position still involves BCL files it's possible that I'll revisit this code but I wouldn't bet on it.

I didn't even know that BCL Convert was released. It's possible that this project is obsolete, if they fixed the performance issues that caused me to write it.

**Comment by brainstorm** [comment]
Haha, no worries, this really got my attention in the past since I was experimenting with [rust-htslib](https://github.com/rust-bio/rust-htslib/pulls?q=is%3Apr+is%3Aclosed+author%3Abrainstorm) and [htsget-rs](https://github.com/umccr/htsget-rs) and considered this "hack" as a brilliant complement for my total world domination "Illumina sequencing total streaming from BCL to bioinfo applications" plans, but I understand if there's no bandwidth, interest in this project anymore... pity ;)
